import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { autoGeneratedMessage, generatedMarker, shellInterception, shellSegments } from "./tool-guards";

const ALL = ["read", "grep", "find", "ls", "edit", "write", "bash"];

describe("generated files", () => {
	test("generator file names and header markers are recognised; markers deep in the code are not", () => {
		expect(generatedMarker("api/service.pb.go", "package api")).toBe("service.pb.go");
		expect(generatedMarker("types.ts", "// Code generated by protoc-gen-ts. DO NOT EDIT.\nexport {}")).toMatch(/Code generated by protoc-gen-ts/i);
		expect(generatedMarker("schema.py", "#!/usr/bin/env python\n# @generated by tool\nx = 1")).toBe("@generated");
		expect(generatedMarker("app.ts", "import x from 'y';\n// this is @generated elsewhere")).toBeNull();
		expect(generatedMarker("README.md", "<!-- @generated -->")).toBeNull();
	});

	describe("on disk", () => {
		let dir: string;
		beforeEach(() => {
			dir = mkdtempSync(join(tmpdir(), "neko-guard-"));
		});
		afterEach(() => rmSync(dir, { recursive: true, force: true }));

		test("an existing generated file is refused with what to do instead; a new file is not", async () => {
			writeFileSync(join(dir, "models.ts"), "/* eslint-disable */\n// Code generated by sqlc. DO NOT EDIT.\n");
			const message = await autoGeneratedMessage(join(dir, "models.ts"), "models.ts");
			expect(message).toContain("Cannot modify auto-generated file: models.ts");
			expect(message).toContain("Regenerate the file");
			expect(await autoGeneratedMessage(join(dir, "new.pb.go"), "new.pb.go")).toBeNull();
		});
	});
});

describe("shell interception", () => {
	test("one-liners with a dedicated tool are redirected, in bash and in PowerShell", () => {
		expect(shellInterception("cat src/app.ts", ALL)).toContain("`read`");
		expect(shellInterception("cd src && rg TODO", ALL)).toContain("`grep`");
		expect(shellInterception("sed -i 's/a/b/' x.ts", ALL)).toContain("`edit`");
		expect(shellInterception('echo "hi" > out.txt', ALL)).toContain("`write`");
		expect(shellInterception("Get-Content .\\src\\app.ts", ALL)).toContain("`read`");
		expect(shellInterception("Select-String -Path *.ts -Pattern TODO", ALL)).toContain("`grep`");
		expect(shellInterception("(Get-Content a.ts) -replace 'x','y' | Set-Content a.ts", ALL)).toContain("`edit`");
		expect(shellInterception("Get-ChildItem -Recurse -Filter *.json", ALL)).toContain("`find`");
	});

	test("what no tool replaces runs: pipes, following a log, discarding output, bash's own type", () => {
		expect(shellInterception("git log --oneline | head -20", ALL)).toBeNull();
		expect(shellInterception("tail -f server.log", ALL)).toBeNull();
		expect(shellInterception("echo done > /dev/null", ALL)).toBeNull();
		expect(shellInterception('echo "a -> b"', ALL)).toBeNull();
		expect(shellInterception("npm test 2>&1", ALL)).toBeNull();
		expect(shellInterception("type node", ALL)).toBeNull();
		expect(shellInterception("git grep -n TODO", ALL)).toBeNull();
	});

	test("a rule whose tool the mode does not offer stays out of the way", () => {
		expect(shellInterception("cat a.ts", ["bash"])).toBeNull();
	});

	test("segments split outside quotes, and piped ones are marked", () => {
		expect(shellSegments('echo "a && b" && cat x | wc -l; ls')).toEqual([
			{ text: 'echo "a && b"', piped: false },
			{ text: "cat x", piped: false },
			{ text: "wc -l", piped: true },
			{ text: "ls", piped: false },
		]);
	});
});
