import { open } from "node:fs/promises";
import { basename } from "node:path";

/**
 * Two checks the tool gate runs before a call, adapted from oh-my-pi (MIT):
 * one refuses edits to generated files, the other steers shell one-liners to
 * the tool built for the job. Both answer with a reason the model can act on,
 * never with a silent refusal.
 */

// ── Generated files ─────────────────────────────────────────────────────────

/** Names only a generator writes; these are refused without reading the file. */
const GENERATED_NAMES = [
	/^zz_generated\./,
	/\.pb\.(?:go|cc|h|c|js|ts)$/,
	/_pb2(?:_grpc)?\.py$/,
	/\.gen\.(?:go|ts|js|py)$/,
	/\.swagger\.json$/,
	/\.mocks?\.(?:go|ts|js)$/,
];

const KNOWN_GENERATORS =
	"(?:protoc(?:-gen-[\\w-]+)?|sqlc|buf|swagger(?:-codegen)?|openapi(?:-generator)?|grpc-gateway|mockery|stringer|easyjson|deepcopy-gen|defaulter-gen|conversion-gen|client-gen|lister-gen|informer-gen|kysely-codegen|napi-rs)";

const GENERATED_MARKERS = [
	/@generated\b/i,
	/\bcode\s+generated\s+by\s+[a-z0-9_.-]+/i,
	/\bcode\s+generated\b.*\bdo\s+not\s+edit\b/i,
	/\bthis\s+file\s+was\s+automatically\s+generated\b/i,
	new RegExp(`\\bgenerated\\s+by\\s+${KNOWN_GENERATORS}\\b`, "i"),
];

type CommentStyle = "slash" | "hash" | "sql" | "html";

function commentStyle(name: string): CommentStyle | null {
	const lower = name.toLowerCase();
	if (["dockerfile", "makefile", "justfile"].includes(lower)) return "hash";
	const extension = lower.includes(".") ? lower.slice(lower.lastIndexOf(".") + 1) : "";
	if (["c", "cc", "cpp", "cs", "dart", "go", "h", "hpp", "java", "js", "jsx", "kt", "kts", "mjs", "cjs", "php", "rs", "scala", "swift", "ts", "tsx"].includes(extension))
		return "slash";
	if (["py", "rb", "sh", "bash", "zsh", "yml", "yaml", "toml", "ini", "cfg", "conf", "env", "pl", "r"].includes(extension)) return "hash";
	if (extension === "sql") return "sql";
	if (["html", "htm", "xml", "svg", "xhtml"].includes(extension)) return "html";
	return null;
}

/**
 * The comment block a file opens with. Only there does a marker count: the
 * same words further down are usually code that talks about generation.
 */
function leadingComment(content: string, style: CommentStyle): string {
	const out: string[] = [];
	let inBlock = false;
	let started = false;
	const lines = content.replace(/^﻿/, "").split(/\r?\n/).slice(0, 40);
	for (const [index, raw] of lines.entries()) {
		const line = raw.trim();
		if (index === 0 && line.startsWith("#!")) continue;
		if (inBlock) {
			out.push(line);
			inBlock = !line.includes(style === "html" ? "-->" : "*/");
			continue;
		}
		if (!line) {
			if (started) out.push("");
			continue;
		}
		const opensBlock = (style === "slash" && line.startsWith("/*")) || (style === "html" && line.startsWith("<!--"));
		const isComment =
			opensBlock ||
			(style === "slash" && line.startsWith("//")) ||
			(style === "hash" && line.startsWith("#")) ||
			(style === "sql" && line.startsWith("--"));
		if (!isComment) break;
		started = true;
		out.push(line);
		if (opensBlock) inBlock = !line.includes(style === "html" ? "-->" : "*/");
	}
	return out.join("\n");
}

/** What marks `content` (the start of a file named `name`) as generated, or null. */
export function generatedMarker(name: string, content: string): string | null {
	const file = basename(name.replace(/\\/g, "/"));
	if (GENERATED_NAMES.some((pattern) => pattern.test(file))) return file;
	const style = commentStyle(file);
	if (!style) return null;
	const header = leadingComment(content, style);
	for (const pattern of GENERATED_MARKERS) {
		const found = pattern.exec(header);
		if (found) return found[0];
	}
	return null;
}

/**
 * The refusal for editing `absolutePath`, or null when it is not generated.
 * A file that does not exist yet is being created, which is never an edit of
 * generated output.
 */
export async function autoGeneratedMessage(absolutePath: string, displayPath: string): Promise<string | null> {
	let head = "";
	try {
		const handle = await open(absolutePath, "r");
		try {
			const buffer = Buffer.alloc(1024);
			const { bytesRead } = await handle.read(buffer, 0, buffer.length, 0);
			head = buffer.subarray(0, bytesRead).toString("utf8");
		} finally {
			await handle.close();
		}
	} catch {
		return null;
	}
	const marker = generatedMarker(absolutePath, head);
	if (!marker) return null;
	return [
		`Cannot modify auto-generated file: ${displayPath}`,
		"",
		`It appears to be generated (detected marker: "${marker}"). Edits here are overwritten the next time it is generated. Instead:`,
		"1. Find the source file or the generator's configuration",
		"2. Make the change there",
		"3. Regenerate the file",
		"If the user explicitly asked for this file to be edited by hand, say so and ask them to confirm.",
	].join("\n");
}

// ── Shell one-liners ────────────────────────────────────────────────────────

interface InterceptRule {
	pattern: RegExp;
	/** The tool to use instead; the rule is skipped when it is not available. */
	tool: string;
	message: string;
}

/**
 * Commands that have a dedicated tool. The tools are better at the job — they
 * page long output, respect the workspace, and record edits for checkpoints,
 * which a shell write bypasses — so the shell call is refused with a pointer.
 *
 * PowerShell forms are included: on Windows the model reaches for
 * Get-Content and Set-Content as readily as cat and sed elsewhere.
 */
const RULES: InterceptRule[] = [
	{
		pattern: /^\s*(?:cat|head|less|more)\s+(?!.*<<)|^\s*tail\s+(?!.*(?:-f|--follow|-F)\b)/,
		tool: "read",
		message: "Use the `read` tool instead of cat/head/tail — it pages long files and reads PDFs, notebooks and archives too.",
	},
	{
		// `type` only with a file-looking argument: in bash, `type node` asks what node is.
		pattern: /^\s*(?:Get-Content|gc)\s+(?!.*-Wait\b)|^\s*type\s+["']?[\w./\\:-]+\.\w+["']?\s*$/i,
		tool: "read",
		message: "Use the `read` tool instead of Get-Content/type — it pages long files and reads PDFs, notebooks and archives too.",
	},
	{
		pattern: /^\s*(?:grep|egrep|fgrep|rg|ripgrep|ag|ack)\s+/,
		tool: "grep",
		message: "Use the `grep` tool instead of grep/rg — it respects .gitignore and returns structured matches.",
	},
	{
		pattern: /^\s*(?:Select-String|sls|findstr)\s+/i,
		tool: "grep",
		message: "Use the `grep` tool instead of Select-String/findstr — it respects .gitignore and returns structured matches.",
	},
	{
		pattern: /^\s*(?:find|fd)\s+.*(?:-i?name|-type|--type|--glob|-e\s)/,
		tool: "find",
		message: "Use the `find` tool instead of find/fd for locating files by name.",
	},
	{
		pattern: /^\s*(?:Get-ChildItem|gci|ls|dir)\s+.*-Recurse\b.*-(?:Filter|Include)\b|^\s*(?:Get-ChildItem|gci|ls|dir)\s+.*-(?:Filter|Include)\b.*-Recurse\b/i,
		tool: "find",
		message: "Use the `find` tool instead of Get-ChildItem -Recurse -Filter for locating files by name.",
	},
	{
		pattern: /^\s*sed\s+(?:-[a-zA-Z]*i|--in-place)|^\s*perl\s+.*-[pn]?i\b|^\s*awk\s+.*-i\s+inplace/,
		tool: "edit",
		message: "Use the `edit` tool instead of sed -i/perl -i — its changes are recorded, so a checkpoint can undo them.",
	},
	{
		pattern: /^\s*\(?\s*(?:Get-Content|gc)\s+.*\)\s*.*-replace\b.*\|\s*(?:Set-Content|Out-File)\b/i,
		tool: "edit",
		message: "Use the `edit` tool instead of Get-Content … -replace … | Set-Content — its changes are recorded, so a checkpoint can undo them.",
	},
	{
		pattern: /^\s*(?:Set-Content|Add-Content|Out-File|New-Item\s+.*-Value\b)/i,
		tool: "write",
		message: "Use the `write` tool (or `edit`) instead of Set-Content/Out-File — its changes are recorded, so a checkpoint can undo them.",
	},
	{
		// A redirect outside quotes into something that looks like a file; `/dev/null`,
		// `2>&1` and `echo "a -> b"` all pass.
		pattern: /^\s*(?:echo|printf|cat\s*<<)\s+(?:[^"'>]|"[^"]*"|'[^']*')*(?<![0-9&])>{1,2}\s*(?!\/dev\/(?:null|tty|stdout|stderr)\b|&)[$\w./~"'-]/,
		tool: "write",
		message: "Use the `write` tool instead of echo/cat redirection — its changes are recorded, so a checkpoint can undo them.",
	},
];

interface Segment {
	text: string;
	/** Reads the previous command's output through `|`, which no file tool can stand in for. */
	piped: boolean;
}

/** Split a command line at `;`, `&&`, `||` and `|` outside quotes. */
export function shellSegments(command: string): Segment[] {
	const segments: Segment[] = [];
	let current = "";
	let quote: '"' | "'" | null = null;
	let piped = false;
	const flush = (nextPiped: boolean) => {
		if (current.trim()) segments.push({ text: current.trim(), piped });
		current = "";
		piped = nextPiped;
	};
	for (let index = 0; index < command.length; index++) {
		const char = command[index];
		const next = command[index + 1];
		if (quote) {
			if (char === "\\" && quote === '"' && next !== undefined) {
				current += char + next;
				index++;
				continue;
			}
			if (char === quote) quote = null;
			current += char;
			continue;
		}
		if (char === '"' || char === "'") {
			quote = char;
			current += char;
			continue;
		}
		if ((char === "&" && next === "&") || (char === "|" && next === "|")) {
			flush(false);
			index++;
			continue;
		}
		if (char === ";" || char === "\n") {
			flush(false);
			continue;
		}
		if (char === "|") {
			flush(true);
			continue;
		}
		current += char;
	}
	flush(false);
	return segments;
}

/**
 * The refusal for running `command` in a shell, or null to let it run.
 * `available` is the tool set the session has right now: a rule pointing at a
 * tool the mode does not offer would leave the model with no way forward.
 */
export function shellInterception(command: string, available: readonly string[]): string | null {
	// The whole line as well as its parts: a rule like `(Get-Content f) -replace … |
	// Set-Content f` is only visible across the pipe.
	const candidates = [command.trim(), ...shellSegments(command).filter((segment) => !segment.piped).map((segment) => segment.text)];
	for (const rule of RULES) {
		if (!available.includes(rule.tool)) continue;
		if (candidates.some((candidate) => rule.pattern.test(candidate)))
			return `Blocked: ${rule.message}\n\nOriginal command: ${command}`;
	}
	return null;
}
